# Generated by Django 4.1 on 2025-01-02 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_color_number"),
    ]

    operations = []
