# Generated by Django 5.1.3 on 2025-01-02 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_orderitem_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="color",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
