# Generated by Django 5.1.3 on 2025-01-02 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_cartitem_color"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="color",
        ),
    ]
