# Generated by Django 5.1.3 on 2025-01-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_remove_cartitem_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="color",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
