# Generated by Django 5.1.3 on 2025-01-03 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_cartitem_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="color",
            field=models.CharField(max_length=50),
        ),
    ]
