# Generated by Django 5.1.3 on 2025-01-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_cartitem_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
