# Generated by Django 4.1 on 2025-01-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="color",
            name="number",
            field=models.CharField(max_length=100),
        ),
    ]
