# Generated by Django 4.1 on 2025-01-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_products_color_orderitem_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="color",
            field=models.CharField(max_length=100),
        ),
    ]
